/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface User {
    id: bigint;
    nip?: string;
    status: string;
    username: string;
    password: string;
    nama: string;
    createdAt: bigint;
    tandatangan?: string;
    updatedAt: bigint;
    wilayah: string;
}
export interface RKH_Laporan {
    id: bigint;
    status: string;
    metode: string;
    indikator: string;
    tanggal: string;
    createdAt: bigint;
    lokasi: string;
    penyuluh: string;
    detail: string;
    tandatangan?: string;
    updatedAt: bigint;
    waktu: string;
    nomorLaporan: bigint;
    sasaran: string;
    namaKegiatan: string;
}
export interface backendInterface {
    adminLogin(arg0: {
        username: string;
        password: string;
    }): Promise<boolean>;
    approveUser(arg0: {
        userId: bigint;
    }): Promise<boolean>;
    createLaporan(arg0: {
        metode: string;
        indikator: string;
        tanggal: string;
        lokasi: string;
        penyuluh: string;
        detail: string;
        waktu: string;
        sasaran: string;
        namaKegiatan: string;
    }): Promise<{
        id: bigint;
    }>;
    getAllLaporan(arg0: {
    }): Promise<Array<RKH_Laporan>>;
    getAllUsers(arg0: {
    }): Promise<Array<User>>;
    getLaporanByPenyuluh(arg0: {
        penyuluh: string;
    }): Promise<Array<RKH_Laporan>>;
    isUsernameTaken(arg0: {
        username: string;
    }): Promise<boolean>;
    loginUser(arg0: {
        username: string;
        password: string;
    }): Promise<User | null>;
    registerUser(arg0: {
        nip?: string;
        username: string;
        password: string;
        nama: string;
        tandatangan?: string;
        wilayah: string;
    }): Promise<{
        userId: bigint;
    }>;
}
import type { RKH_Laporan as _RKH_Laporan, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminLogin(arg0: {
        username: string;
        password: string;
    }): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async approveUser(arg0: {
        userId: bigint;
    }): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0);
            return result;
        }
    }
    async createLaporan(arg0: {
        metode: string;
        indikator: string;
        tanggal: string;
        lokasi: string;
        penyuluh: string;
        detail: string;
        waktu: string;
        sasaran: string;
        namaKegiatan: string;
    }): Promise<{
        id: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createLaporan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLaporan(arg0);
            return result;
        }
    }
    async getAllLaporan(arg0: {
    }): Promise<Array<RKH_Laporan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLaporan(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLaporan(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(arg0: {
    }): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLaporanByPenyuluh(arg0: {
        penyuluh: string;
    }): Promise<Array<RKH_Laporan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLaporanByPenyuluh(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLaporanByPenyuluh(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async isUsernameTaken(arg0: {
        username: string;
    }): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameTaken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameTaken(arg0);
            return result;
        }
    }
    async loginUser(arg0: {
        username: string;
        password: string;
    }): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: {
        nip?: string;
        username: string;
        password: string;
        nama: string;
        tandatangan?: string;
        wilayah: string;
    }): Promise<{
        userId: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_record_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_record_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_RKH_Laporan_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RKH_Laporan): RKH_Laporan {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_User_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    metode: string;
    indikator: string;
    tanggal: string;
    createdAt: bigint;
    lokasi: string;
    penyuluh: string;
    detail: string;
    tandatangan: [] | [string];
    updatedAt: bigint;
    waktu: string;
    nomorLaporan: bigint;
    sasaran: string;
    namaKegiatan: string;
}): {
    id: bigint;
    status: string;
    metode: string;
    indikator: string;
    tanggal: string;
    createdAt: bigint;
    lokasi: string;
    penyuluh: string;
    detail: string;
    tandatangan?: string;
    updatedAt: bigint;
    waktu: string;
    nomorLaporan: bigint;
    sasaran: string;
    namaKegiatan: string;
} {
    return {
        id: value.id,
        status: value.status,
        metode: value.metode,
        indikator: value.indikator,
        tanggal: value.tanggal,
        createdAt: value.createdAt,
        lokasi: value.lokasi,
        penyuluh: value.penyuluh,
        detail: value.detail,
        tandatangan: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.tandatangan)),
        updatedAt: value.updatedAt,
        waktu: value.waktu,
        nomorLaporan: value.nomorLaporan,
        sasaran: value.sasaran,
        namaKegiatan: value.namaKegiatan
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nip: [] | [string];
    status: string;
    username: string;
    password: string;
    nama: string;
    createdAt: bigint;
    tandatangan: [] | [string];
    updatedAt: bigint;
    wilayah: string;
}): {
    id: bigint;
    nip?: string;
    status: string;
    username: string;
    password: string;
    nama: string;
    createdAt: bigint;
    tandatangan?: string;
    updatedAt: bigint;
    wilayah: string;
} {
    return {
        id: value.id,
        nip: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.nip)),
        status: value.status,
        username: value.username,
        password: value.password,
        nama: value.nama,
        createdAt: value.createdAt,
        tandatangan: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.tandatangan)),
        updatedAt: value.updatedAt,
        wilayah: value.wilayah
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RKH_Laporan>): Array<RKH_Laporan> {
    return value.map((x)=>from_candid_RKH_Laporan_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n6(_uploadFile, _downloadFile, x));
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nip?: string;
    username: string;
    password: string;
    nama: string;
    tandatangan?: string;
    wilayah: string;
}): {
    nip: [] | [string];
    username: string;
    password: string;
    nama: string;
    tandatangan: [] | [string];
    wilayah: string;
} {
    return {
        nip: value.nip ? candid_some(value.nip) : candid_none(),
        username: value.username,
        password: value.password,
        nama: value.nama,
        tandatangan: value.tandatangan ? candid_some(value.tandatangan) : candid_none(),
        wilayah: value.wilayah
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
